#include <avr/pgmspace.h>
#include <Stepper.h>
#include <StepperMulti.h>

const int stepsPerRevolution = 200;
#define tempo 122

#define note_16 (1000 * 15) / tempo
#define note_1 note_16 * 16
#define note_2 note_16 * 8
#define note_4 note_16 * 4
#define note_8 note_16 * 2
#define note_32 note_16 / 2
#define note_64 note_16 / 4
#define note_12 note_1 + note_2
#define note_24 note_2 + note_4
#define note_48 note_4 + note_8
#define note_86 note_8 + note_16

#define p_C1 33
#define p_C1F 35
#define p_D1 37
#define p_E1B 39
#define p_E1 41
#define p_F1 44
#define p_F1F 46
#define p_G1 49
#define p_G1F 52
#define p_A1 55
#define p_B1B 58
#define p_B1 62
#define p_C2 65
#define p_C2F 69
#define p_D2 73
#define p_E2B 78
#define p_E2 82
#define p_F2 87
#define p_F2F 93
#define p_G2 98
#define p_G2F 104
#define p_A2 110
#define p_B2B 117
#define p_B2 124
#define p_C3 131
#define p_C3F 139
#define p_D3 147
#define p_E3B 156
#define p_E3 165
#define p_F3 175
#define p_F3F 185
#define p_G3 196
#define p_G3F 208
#define p_A3 220
#define p_B3B 233
#define p_B3 247
#define p_C4 262
#define p_C4F 277
#define p_D4 294
#define p_E4B 311
#define p_E4 330
#define p_F4 349
#define p_F4F 370
#define p_G4 392
#define p_G4F 415
#define p_A4 440
#define p_B4B 466
#define p_B4 494
#define p_C5 523
#define p_C5F 554
#define p_D5 587
#define p_E5B 622
#define p_E5 659
#define p_F5 699
#define p_F5F 740
#define p_G5 784
#define p_G5F 831
#define p_A5 880
#define p_B5B 932
#define p_B5 988
#define p_C6 1047
#define p_C6F 1109
#define p_D6 1175
#define p_E6B 1245

const PROGMEM int HIGH_NOTE[][3] =
    {

        //1
        {note_1},

        {note_1},

        {note_1},

        {note_1},

        //2
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_G5},
        {note_4 + note_16, p_E5},
        {note_4},

        {note_1},

        {note_1},

        //3
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_G5},
        {note_4 + note_16, p_E5},
        {note_4},

        {note_8},
        {note_8, p_E5},
        {note_16, p_G5},
        {note_8, p_A5},
        {note_2 + note_16, p_E5},

        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3},
        {note_16},
        {note_8, p_G3},
        {note_16},
        {note_8, p_G3},

        //4
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_4 + note_16, p_E5},
        {note_4},

        {note_8},
        {note_8 - note_64, p_A4},
        {note_64},
        {note_16, p_A4},
        {note_8, p_G5},
        {note_2 + note_16, p_E5},

        {note_8},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},

        //5
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_G5},
        {note_4 + note_16, p_E5},
        {note_4},

        {note_8},
        {note_8, p_E5},
        {note_16, p_G5},
        {note_8, p_A5},
        {note_2 + note_16, p_E5},

        {note_8},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_F4},
        {note_16},
        {note_16, p_F4},
        {note_8, p_G5},
        {note_8, p_F5},

        //6
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_8 + note_16, p_E5B},
        {note_8, p_D5},
        {note_8, p_C5},
        {note_8, p_A4},

        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},

        {note_8, p_A3},
        {note_8},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_4, p_A3},
        {note_4},

        //7
        {note_1},
        {note_1},
        {note_1},
        {note_1},
        {note_1},
        {note_1},
        {note_1},
        {note_1},

        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},

        {note_16 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},

        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},

        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},

        {note_16 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},
        {note_16 - note_64, p_F5F},
        {note_64},
        {note_8 - note_64, p_F5F},
        {note_64},

        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},

        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_16 - note_64, p_E5},
        {note_64},
        {note_8 - note_64, p_E5},
        {note_64},
        {note_16, p_E5},
        {note_8 + note_16},
        {note_8, p_D5},
        {note_8, p_E3B},

        {note_16, p_E5},
        {note_16},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_16, p_F4F},
        {note_16},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_G5},
        {note_4 + note_16, p_E5},
        {note_4},

        {note_8},
        {note_8, p_E5},
        {note_16, p_G5},
        {note_8, p_A5},
        {note_2 + note_16, p_E5},

        {note_8},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_F3},
        {note_16},
        {note_8, p_F3},
        {note_16},
        {note_8, p_F3},

        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},

        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_4 + note_16, p_E5},
        {note_4},

        {note_8},
        {note_8 - note_64, p_A4},
        {note_64},
        {note_16, p_A4},
        {note_8, p_G5},
        {note_2 + note_16, p_E5},

        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_4, p_E5},
        {note_4},
        {note_8},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_G5},
        {note_4 + note_16, p_E5},
        {note_4},
        {note_8},
        {note_8, p_E5},
        {note_16, p_G5},
        {note_8, p_A5},
        {note_2 + note_16, p_E5},
        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3},
        {note_16},
        {note_8, p_G3},
        {note_16},
        {note_8, p_G3},
        {note_8, p_E5},
        {note_8, p_A4},
        {note_16, p_C5},
        {note_8, p_D5},
        {note_16 + note_2, p_E5},
        {note_4 + note_8},
        {note_4, p_C6},
        {note_8, p_B5},
        {note_8, p_G5},
        {note_4, p_A5},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_8},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},
        {note_16},
        {note_8, p_E4},

        {note_2 + note_8},
        {note_8, p_A4},
        {note_8, p_C5},
        {note_16, p_D5},
        {note_16, p_E5},

        {note_8},
        {note_8, p_A4},
        {note_8, p_C5},
        {note_16, p_D5},
        {note_8 + note_16, p_E5B},
        {note_8, p_D5},
        {note_8, p_C5},
        {note_8, p_A4},

        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3},
        {note_16},
        {note_8, p_G3},
        {note_16},
        {note_8, p_G3},

        {note_2 + note_8},
        {note_8, p_A4},
        {note_8, p_C5},
        {note_16, p_D5},
        {note_16, p_E5},

        {note_8},
        {note_8, p_A4},
        {note_8, p_C5},
        {note_16, p_D5},
        {note_8 + note_16, p_E5B},
        {note_8, p_D5},
        {note_8, p_C5},
        {note_8, p_A4},

        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_8},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_16},
        {note_8, p_G3F},
        {note_1},
        {note_1},
        {note_1},
        {note_1},
        {0, 0, 0}};

const PROGMEM int LOW_NOTE[][3] =
    {
        //1
        {note_8 + note_16, p_D3},
        {note_8 + note_16, p_A3},
        {note_4, p_D4},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_D3},
        {note_16, p_E3B},
        {note_8 + note_16, p_E3},
        {note_8 + note_16, p_B3},
        {note_4, p_E4},
        {note_8, p_E3},
        {note_8, p_B3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_4, p_A3},
        {note_8, p_A2},
        {note_8, p_E3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_16, p_B3B},
        {note_4 - note_16, p_B3},
        {note_8, p_A3},
        {note_8, p_E3},
        {note_8, p_E3B},
        {note_4, p_D3},
        {note_8 + note_16, p_A3},
        {note_8 + note_16, p_D4},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_D3},
        {note_16, p_E3B},
        {note_4, p_E3},
        {note_8 + note_16, p_B3},
        {note_8 + note_16, p_E4},
        {note_8, p_E3},
        {note_8, p_B3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_4, p_A3},
        {note_8, p_A2},
        {note_8, p_E3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8, p_A2},
        {note_4 + note_8},
        {note_16, p_A2},
        {note_4 - note_16},
        {note_16, p_A2},
        {note_4 - note_16},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_4, p_A2},
        {note_4 - note_64, p_E3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_G3},
        {note_8, p_G3F},
        {note_16, p_G3},
        {note_8, p_G3F},
        {note_4, p_A2},
        {note_4 - note_64, p_E3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_4, p_A2},
        {note_4 - note_64, p_E3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_8, p_E3B},
        {note_8, p_C3},
        {note_8, p_C3F},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_G3},
        {note_8, p_G3F},
        {note_16, p_G3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_1},

        {note_8 + note_16, p_D3},
        {note_8 + note_16, p_A3},
        {note_4, p_D4},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_D3},
        {note_16, p_E3B},
        {note_8 + note_16, p_E3},
        {note_8 + note_16, p_B3},
        {note_4, p_E4},
        {note_8, p_E3},
        {note_8, p_B3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_4, p_A3},
        {note_8, p_A2},
        {note_8, p_E3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_16, p_B3B},
        {note_4 - note_16, p_B3},
        {note_8, p_A3},
        {note_8, p_E3},
        {note_8, p_E3B},
        {note_8 + note_16, p_D3},
        {note_8 + note_16, p_A3},
        {note_4, p_D4},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_D3},
        {note_16, p_E3B},
        {note_8 + note_16, p_E3},
        {note_8 + note_16, p_B3},
        {note_4, p_E4},
        {note_8, p_E3},
        {note_8, p_B3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_4, p_A3},
        {note_8, p_A2},
        {note_8, p_E3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8, p_A2},
        {note_8, p_A3},
        {note_8, p_B2},
        {note_8, p_B3},
        {note_8, p_C3},
        {note_8, p_C4},
        {note_8, p_C2},
        {note_8, p_C2F},
        {note_4, p_D2},
        {note_4 + note_8 - note_64, p_C3},
        {note_64},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_D2},
        {note_4, p_E2},
        {note_4 + note_8 - note_64, p_D3},
        {note_64},
        {note_8 + note_16, p_B2},
        {note_8 + note_16, p_E2},
        {note_4, p_A1},
        {note_4 + note_8 - note_64, p_C3F},
        {note_64},
        {note_8 + note_16, p_C3F},
        {note_8 + note_16, p_A2},
        {note_4, p_A1},
        {note_4 + note_8 - note_64, p_C3F},
        {note_64},
        {note_8 + note_16, p_C3F},
        {note_8 + note_16, p_A2},
        {note_4, p_D2},
        {note_4 + note_8 - note_64, p_C3},
        {note_64},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_D2},
        {note_4, p_E2},
        {note_4 + note_8 - note_64, p_D3},
        {note_64},
        {note_8 + note_16, p_B2},
        {note_8 + note_16, p_E2},
        {note_4, p_A1},
        {note_4 + note_8 - note_64, p_C3F},
        {note_64},
        {note_8 + note_16, p_C3F},
        {note_8 + note_16, p_A2},
        {note_4, p_A1},
        {note_4 - note_64, p_C3F},
        {note_64},
        {note_8, p_A2, p_C3F},
        {note_8},
        {note_8, p_C3},
        {note_8, p_C3F},
        {note_16, p_D3},
        {note_16},
        {note_2},
        {note_16, p_F3},
        {note_8, p_A4},
        {note_16, p_F3},
        {note_8, p_A4},
        {note_16, p_E3},
        {note_16},
        {note_2},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_4, p_A2},
        {note_4 - note_64, p_E3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_4, p_A2},
        {note_4 - note_64, p_E3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_G3},
        {note_8, p_G3F},
        {note_16, p_G3},
        {note_8, p_G3F},
        {note_4, p_A2},
        {note_4 - note_64, p_E3},
        {note_64},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_16, p_E3},
        {note_8, p_G3F},
        {note_8, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_4, p_D3},
        {note_4 - note_64, p_A3},
        {note_64},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_8, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_A2},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_16, p_E3B},
        {note_8},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_16, p_F3},
        {note_8, p_A3},
        {note_4, p_E3},
        {note_4 - note_64, p_B3},
        {note_64},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_16, p_G3},
        {note_8, p_B3},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_8, p_A2},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_16, p_E3},
        {note_8},
        {note_8, p_D3},
        {note_8 + note_16, p_A3},
        {note_4, p_D4},
        {note_8, p_D3},
        {note_8, p_A3},
        {note_16, p_D3},
        {note_16, p_E3B},
        {note_8 + note_16, p_E3},
        {note_8 + note_16, p_B3},
        {note_4, p_E4},
        {note_8, p_E3},
        {note_8, p_B3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_8 + note_16, p_A2},
        {note_8 + note_16, p_E3},
        {note_4, p_A3},
        {note_8, p_A2},
        {note_8, p_E3},
        {note_16, p_G2},
        {note_16, p_G2F},
        {note_16, p_A2},
        {note_2 + note_4 + note_8},
        {0, 0}};

int i = 0, j = 0;
long prev_time;
long high_prev_time;
long low_prev_time;
int high_note[2] = {0};
int low_note[2] = {0};

Stepper myStepper(stepsPerRevolution, 2, 4, 3, 5);
Stepper myStepper2(stepsPerRevolution, 6, 8, 7, 9); //6879

void setup()
{
  myStepper.setSpeed(200);
  myStepper2.setSpeed(200);
  Serial.begin(9600);

  high_note[0] = pgm_read_word_near(HIGH_NOTE[i] + 0);
  high_note[1] = pgm_read_word_near(HIGH_NOTE[i] + 1);
  low_note[0] = pgm_read_word_near(LOW_NOTE[j] + 0);
  low_note[1] = pgm_read_word_near(LOW_NOTE[j] + 1);

  if (high_note[1] != 0)
    myStepper.setSpeed(high_note[1]);
  else
    myStepper.setSpeed(200);

  if (low_note[1] != 0)
    myStepper2.setSpeed(low_note[1]);
  else
    myStepper2.setSpeed(200);

  prev_time = millis();
  high_prev_time = prev_time;
  low_prev_time = prev_time;
}

void loop()
{
  prev_time = millis();
/*
  if (prev_time - high_prev_time < high_note[0])
  {
    if (high_note[1] != 0)
      myStepper.step(1);
  }
  else
  {
    high_prev_time = millis();
    i++;
    high_note[0] = pgm_read_word_near(HIGH_NOTE[i] + 0);
    high_note[1] = pgm_read_word_near(HIGH_NOTE[i] + 1);
    myStepper.setSpeed(high_note[1]);
  }*/

  if (prev_time - low_prev_time < low_note[0])
  {
    if (low_note[1] != 0)
      myStepper2.step(1);
  }
  else
  {
    low_prev_time = millis();
    j++;
    low_note[0] = pgm_read_word_near(LOW_NOTE[j] + 0);
    low_note[1] = pgm_read_word_near(LOW_NOTE[j] + 1);
    myStepper2.setSpeed(low_note[1]);
  }
  
}
